// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRxO5wbNU6TTImBX_OI_z3mA0aMf2RYTQ',
    appId: '1:240515861982:web:dc7391740d839ad580e14f',
    messagingSenderId: '240515861982',
    projectId: 'rutau-practica-iv',
    authDomain: 'rutau-practica-iv.firebaseapp.com',
    storageBucket: 'rutau-practica-iv.firebasestorage.app',
    measurementId: 'G-2TZ2KFXPHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGAtXzbx5DDFkSlm2TFkPrl-draVwqRY',
    appId: '1:240515861982:android:19529bfa0b4d6bea80e14f',
    messagingSenderId: '240515861982',
    projectId: 'rutau-practica-iv',
    storageBucket: 'rutau-practica-iv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbPZt9gGRHGsxTlfaT-zronki3oL0MU8k',
    appId: '1:240515861982:ios:34aa02544b5dfc6a80e14f',
    messagingSenderId: '240515861982',
    projectId: 'rutau-practica-iv',
    storageBucket: 'rutau-practica-iv.firebasestorage.app',
    iosBundleId: 'com.example.rutau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbPZt9gGRHGsxTlfaT-zronki3oL0MU8k',
    appId: '1:240515861982:ios:34aa02544b5dfc6a80e14f',
    messagingSenderId: '240515861982',
    projectId: 'rutau-practica-iv',
    storageBucket: 'rutau-practica-iv.firebasestorage.app',
    iosBundleId: 'com.example.rutau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRxO5wbNU6TTImBX_OI_z3mA0aMf2RYTQ',
    appId: '1:240515861982:web:9f21a10abdb9355680e14f',
    messagingSenderId: '240515861982',
    projectId: 'rutau-practica-iv',
    authDomain: 'rutau-practica-iv.firebaseapp.com',
    storageBucket: 'rutau-practica-iv.firebasestorage.app',
    measurementId: 'G-H9EWHFDWL8',
  );

}